### ISSUE TITLE
960px grid

### ISSUE THREAD

**Issue by tkapler** [cutestrap/cutestrap#16]
I wonder why you are using 960px grid. This is commonly used because it is easy to divide by 2,3,4,5,6 - so great for 12columns grid. But your grid is implicit, so you are not limited to such size and you can use something, what would use far better the available viewport for different types of common devices, and it would be your great advantage.

**Comment by tylerchilds** [comment]
I do have a few different wrappers with max-widths, one of which is 960px, but I wouldn't say I'm using a 960px grid. For my landing page, I like the readability of the 960px, even on my larger screen, so that was just a choice for that particular website, which I think is still a pretty common width. 

There's also the grid break point for large screens at 960px, but that's just my lower bound for what I'm describing as a large screen. My breakpoints don't target particular device sizes because they're always changing, so they're just estimates for how something should look on a particular screen size.

I'd recommend using the best wrapper for the particular content and if the largest one at 1200px isn't large enough, I can consider adding `wrapper-xlarge` as an option or you don't need to use a wrapper at all, since the grid is always 100% of the width of the parent container.
